export enum Role {
  SUPER_ADMIN = 'SUPER_ADMIN',
  DOCTOR = 'DOCTOR',
  PATIENT = 'PATIENT',
}

export enum UserStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  SUSPENDED = 'SUSPENDED',
}

export enum DoctorStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  SUSPENDED = 'SUSPENDED',
}

export enum PatientStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  SUSPENDED = 'SUSPENDED',
}

export enum ConsultationType {
  IN_CLINIC = 'IN_CLINIC',
  VIDEO = 'VIDEO',
  HOME_VISIT = 'HOME_VISIT',
}

export enum BookingStatus {
  PENDING_PAYMENT = 'PENDING_PAYMENT',
  CONFIRMED = 'CONFIRMED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED_BY_PATIENT = 'CANCELLED_BY_PATIENT',
  CANCELLED_BY_DOCTOR = 'CANCELLED_BY_DOCTOR',
  CANCELLED_BY_SYSTEM = 'CANCELLED_BY_SYSTEM',
  NO_SHOW = 'NO_SHOW',
}

export enum CancelledBy {
  PATIENT = 'PATIENT',
  DOCTOR = 'DOCTOR',
  ADMIN = 'ADMIN',
  SYSTEM = 'SYSTEM',
}

export enum PaymentStatus {
  PENDING = 'PENDING',
  CAPTURED = 'CAPTURED',
  FAILED = 'FAILED',
  REFUNDED = 'REFUNDED',
  PARTIALLY_REFUNDED = 'PARTIALLY_REFUNDED',
}

export enum ConsultationStatus {
  WAITING = 'WAITING',
  ACTIVE = 'ACTIVE',
  COMPLETED = 'COMPLETED',
  ABANDONED = 'ABANDONED',
  TECHNICAL_FAILURE = 'TECHNICAL_FAILURE',
}

export enum NotifType {
  BOOKING_CONFIRMED = 'BOOKING_CONFIRMED',
  BOOKING_REMINDER_24H = 'BOOKING_REMINDER_24H',
  BOOKING_REMINDER_1H = 'BOOKING_REMINDER_1H',
  BOOKING_REMINDER_15M = 'BOOKING_REMINDER_15M',
  CONSULT_STARTED = 'CONSULT_STARTED',
  CONSULT_ENDED = 'CONSULT_ENDED',
  PRESCRIPTION_READY = 'PRESCRIPTION_READY',
  BOOKING_CANCELLED = 'BOOKING_CANCELLED',
  DOCTOR_APPROVED = 'DOCTOR_APPROVED',
  DOCTOR_REJECTED = 'DOCTOR_REJECTED',
  REVIEW_REQUEST = 'REVIEW_REQUEST',
  PAYOUT_PROCESSED = 'PAYOUT_PROCESSED',
}

export enum NotifChannel {
  IN_APP = 'IN_APP',
  EMAIL = 'EMAIL',
  SMS = 'SMS',
  PUSH = 'PUSH',
  WHATSAPP = 'WHATSAPP',
}

export enum BlogStatus {
  DRAFT = 'DRAFT',
  PUBLISHED = 'PUBLISHED',
  ARCHIVED = 'ARCHIVED',
}

export enum PharmacyOrderStatus {
  PLACED = 'PLACED',
  VERIFIED = 'VERIFIED',
  PACKED = 'PACKED',
  SHIPPED = 'SHIPPED',
  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED',
}

export enum PayoutStatus {
  REQUESTED = 'REQUESTED',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
}

export enum CouponApplicable {
  BOOKING = 'BOOKING',
  PHARMACY = 'PHARMACY',
  BOTH = 'BOTH',
}
