-- DocNear v1.1 — Initial migration
-- Engine: PostgreSQL 16 + PostGIS
-- Generated: 2026-05-21
--
-- IMPORTANT: This file was hand-authored, not auto-generated by Prisma.
-- It covers features Prisma cannot express:
--   1. PostGIS GEOGRAPHY GENERATED ALWAYS AS column (clinics.location)
--   2. Partial UNIQUE INDEX on bookings (WHERE active statuses only)
--   3. Partial UNIQUE INDEX on doctor_specialities (one primary per doctor)
--   4. RANGE-partitioned tables (notifications, audit_logs) with monthly partitions
--   5. Custom CHECK constraints not supported by Prisma
--
-- Run via: pnpm db:migrate  (dev)  |  pnpm db:deploy  (prod/CI)

BEGIN;

-- ─────────────────────────────────────────────────────────────────────────────
-- EXTENSIONS
-- ─────────────────────────────────────────────────────────────────────────────
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE EXTENSION IF NOT EXISTS postgis;

-- ─────────────────────────────────────────────────────────────────────────────
-- ENUMERATIONS
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TYPE role_enum AS ENUM ('SUPER_ADMIN', 'DOCTOR', 'PATIENT');
CREATE TYPE user_status_enum AS ENUM ('PENDING', 'APPROVED', 'REJECTED', 'SUSPENDED');
CREATE TYPE doctor_status_enum AS ENUM ('PENDING', 'APPROVED', 'REJECTED', 'SUSPENDED');
CREATE TYPE patient_status_enum AS ENUM ('PENDING', 'APPROVED', 'SUSPENDED');
CREATE TYPE consultation_type_enum AS ENUM ('IN_CLINIC', 'VIDEO', 'HOME_VISIT');

-- v1.1: CANCELLED_BY_SYSTEM added for BullMQ slot-expiry
CREATE TYPE booking_status_enum AS ENUM (
  'PENDING_PAYMENT', 'CONFIRMED', 'IN_PROGRESS',
  'COMPLETED', 'CANCELLED_BY_PATIENT', 'CANCELLED_BY_DOCTOR',
  'CANCELLED_BY_SYSTEM', 'NO_SHOW'
);
-- v1.1: SYSTEM added for BullMQ auto-expiry
CREATE TYPE cancelled_by_enum AS ENUM ('PATIENT', 'DOCTOR', 'ADMIN', 'SYSTEM');

CREATE TYPE payment_status_enum AS ENUM (
  'PENDING', 'CAPTURED', 'FAILED', 'REFUNDED', 'PARTIALLY_REFUNDED'
);
CREATE TYPE refund_status_enum AS ENUM ('PENDING', 'PROCESSED', 'FAILED');

-- v1.1: TECHNICAL_FAILURE added
CREATE TYPE consultation_status_enum AS ENUM (
  'WAITING', 'ACTIVE', 'COMPLETED', 'ABANDONED', 'TECHNICAL_FAILURE'
);

CREATE TYPE notif_type_enum AS ENUM (
  'BOOKING_CONFIRMED', 'BOOKING_REMINDER_24H', 'BOOKING_REMINDER_1H',
  'BOOKING_REMINDER_15M', 'CONSULT_STARTED', 'CONSULT_ENDED',
  'PRESCRIPTION_READY', 'BOOKING_CANCELLED', 'DOCTOR_APPROVED',
  'DOCTOR_REJECTED', 'REVIEW_REQUEST', 'PAYOUT_PROCESSED'
);
CREATE TYPE notif_channel_enum AS ENUM ('IN_APP', 'EMAIL', 'SMS', 'PUSH', 'WHATSAPP');
CREATE TYPE notif_status_enum AS ENUM ('PENDING', 'SENT', 'FAILED', 'DELIVERED');

-- v1.1: applicable_to for scoped coupons
CREATE TYPE coupon_type_enum AS ENUM ('FLAT', 'PERCENT');
CREATE TYPE coupon_applicable_enum AS ENUM ('BOOKING', 'PHARMACY', 'BOTH');

CREATE TYPE blog_status_enum AS ENUM ('DRAFT', 'PUBLISHED', 'ARCHIVED');
CREATE TYPE pharmacy_order_status_enum AS ENUM (
  'PLACED', 'VERIFIED', 'PACKED', 'SHIPPED', 'DELIVERED', 'CANCELLED'
);
CREATE TYPE payout_status_enum AS ENUM ('REQUESTED', 'PROCESSING', 'COMPLETED', 'FAILED');

-- ─────────────────────────────────────────────────────────────────────────────
-- USERS
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE users (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  -- v1.1: PII encrypted; hash shadow columns for uniqueness + lookups
  email_enc       BYTEA,
  email_hash      TEXT UNIQUE,
  phone_enc       BYTEA,
  phone_hash      TEXT UNIQUE,
  password_hash   TEXT,
  role            role_enum NOT NULL,
  status          user_status_enum NOT NULL DEFAULT 'PENDING',
  first_name      TEXT NOT NULL,
  last_name       TEXT NOT NULL,
  avatar_url      TEXT,
  google_id       TEXT UNIQUE,
  email_verified  BOOLEAN NOT NULL DEFAULT FALSE,
  phone_verified  BOOLEAN NOT NULL DEFAULT FALSE,
  last_login_at   TIMESTAMPTZ,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted_at      TIMESTAMPTZ,
  CONSTRAINT at_least_one_contact CHECK (email_hash IS NOT NULL OR phone_hash IS NOT NULL)
);

CREATE INDEX idx_users_role ON users(role);
CREATE INDEX idx_users_status ON users(status);
CREATE INDEX idx_users_deleted_at ON users(deleted_at) WHERE deleted_at IS NULL;
CREATE INDEX idx_users_google ON users(google_id) WHERE google_id IS NOT NULL;

-- ─────────────────────────────────────────────────────────────────────────────
-- DOCTOR PROFILES
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE doctor_profiles (
  id                      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id                 UUID NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
  mci_reg_no              TEXT NOT NULL UNIQUE,
  qualifications          TEXT[] NOT NULL DEFAULT '{}',
  bio                     TEXT,
  experience_years        INTEGER NOT NULL DEFAULT 0,
  gender                  TEXT,
  languages               TEXT[] NOT NULL DEFAULT '{"English"}',
  consultation_fee_clinic INTEGER NOT NULL DEFAULT 0,
  consultation_fee_online INTEGER NOT NULL DEFAULT 0,
  slot_duration_minutes   INTEGER NOT NULL DEFAULT 15,
  registration_doc_url    TEXT,
  id_proof_url            TEXT,
  verification_status     doctor_status_enum NOT NULL DEFAULT 'PENDING',
  rejection_reason        TEXT,
  verified_by             UUID REFERENCES users(id),
  verified_at             TIMESTAMPTZ,
  avg_rating              FLOAT NOT NULL DEFAULT 0.0,
  total_reviews           INTEGER NOT NULL DEFAULT 0,
  total_consultations     INTEGER NOT NULL DEFAULT 0,
  slug                    TEXT NOT NULL UNIQUE,
  created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at              TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_doctor_profiles_verification ON doctor_profiles(verification_status);
CREATE INDEX idx_doctor_profiles_rating ON doctor_profiles(avg_rating DESC)
  WHERE verification_status = 'APPROVED';
CREATE INDEX idx_doctor_profiles_fee ON doctor_profiles(consultation_fee_clinic)
  WHERE verification_status = 'APPROVED';

-- ─────────────────────────────────────────────────────────────────────────────
-- DOCTOR BANK ACCOUNTS  (v1.1 NEW)
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE doctor_bank_accounts (
  id                        UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  doctor_id                 UUID NOT NULL UNIQUE REFERENCES doctor_profiles(id) ON DELETE CASCADE,
  account_number_enc        BYTEA NOT NULL,
  last4                     TEXT NOT NULL,
  ifsc_code                 TEXT NOT NULL,
  holder_name               TEXT NOT NULL,
  bank_name                 TEXT,
  razorpay_contact_id       TEXT,
  razorpay_fund_account_id  TEXT,
  is_verified               BOOLEAN NOT NULL DEFAULT FALSE,
  created_at                TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at                TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ─────────────────────────────────────────────────────────────────────────────
-- PATIENT PROFILES
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE patient_profiles (
  id                      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id                 UUID NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
  dob_enc                 BYTEA,
  blood_group             TEXT,
  gender                  TEXT,
  allergies_enc           BYTEA,
  chronic_conditions_enc  BYTEA,
  verification_status     patient_status_enum NOT NULL DEFAULT 'PENDING',
  created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at              TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ─────────────────────────────────────────────────────────────────────────────
-- FAMILY MEMBERS
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE family_members (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  patient_id  UUID NOT NULL REFERENCES patient_profiles(id) ON DELETE CASCADE,
  name        TEXT NOT NULL,
  relation    TEXT NOT NULL,
  dob         DATE,
  gender      TEXT,
  blood_group TEXT,
  allergies   TEXT[] NOT NULL DEFAULT '{}',
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_family_members_patient ON family_members(patient_id);

-- ─────────────────────────────────────────────────────────────────────────────
-- SPECIALITIES
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE specialities (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name        TEXT NOT NULL UNIQUE,
  slug        TEXT NOT NULL UNIQUE,
  icon_url    TEXT,
  description TEXT,
  is_active   BOOLEAN NOT NULL DEFAULT TRUE,
  sort_order  INTEGER NOT NULL DEFAULT 0,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_specialities_active ON specialities(sort_order) WHERE is_active = TRUE;

-- ─────────────────────────────────────────────────────────────────────────────
-- DOCTOR SPECIALITIES (composite PK)
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE doctor_specialities (
  doctor_id     UUID NOT NULL REFERENCES doctor_profiles(id) ON DELETE CASCADE,
  speciality_id UUID NOT NULL REFERENCES specialities(id) ON DELETE CASCADE,
  is_primary    BOOLEAN NOT NULL DEFAULT FALSE,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (doctor_id, speciality_id)
);

CREATE INDEX idx_doc_spec_speciality ON doctor_specialities(speciality_id);

-- v1.1: at most one primary speciality per doctor
CREATE UNIQUE INDEX idx_doc_spec_one_primary
  ON doctor_specialities(doctor_id)
  WHERE is_primary = TRUE;

-- ─────────────────────────────────────────────────────────────────────────────
-- CITIES
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE cities (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name       TEXT NOT NULL,
  state      TEXT NOT NULL,
  slug       TEXT NOT NULL UNIQUE,
  lat        FLOAT NOT NULL,
  lng        FLOAT NOT NULL,
  is_active  BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_cities_active ON cities(name) WHERE is_active = TRUE;

-- ─────────────────────────────────────────────────────────────────────────────
-- CLINICS  (v1.1: location is GENERATED from lat/lng via PostGIS)
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE clinics (
  id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  doctor_id      UUID NOT NULL REFERENCES doctor_profiles(id) ON DELETE CASCADE,
  name           TEXT NOT NULL,
  address_line1  TEXT NOT NULL,
  address_line2  TEXT,
  city_id        UUID NOT NULL REFERENCES cities(id),
  pincode        TEXT NOT NULL,
  lat            FLOAT NOT NULL,
  lng            FLOAT NOT NULL,
  -- v1.1: generated column — no manual sync or triggers needed
  location       GEOGRAPHY GENERATED ALWAYS AS (ST_MakePoint(lng, lat)::geography) STORED,
  phone          TEXT,
  working_hours  JSONB NOT NULL DEFAULT '{}',
  is_active      BOOLEAN NOT NULL DEFAULT TRUE,
  sort_order     INTEGER NOT NULL DEFAULT 0,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_clinics_doctor ON clinics(doctor_id);
CREATE INDEX idx_clinics_location ON clinics USING GIST(location);
CREATE INDEX idx_clinics_city ON clinics(city_id) WHERE is_active = TRUE;

-- ─────────────────────────────────────────────────────────────────────────────
-- DOCTOR AVAILABILITY
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE doctor_availability (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  doctor_id     UUID NOT NULL REFERENCES doctor_profiles(id) ON DELETE CASCADE,
  clinic_id     UUID REFERENCES clinics(id) ON DELETE SET NULL,
  day_of_week   INTEGER NOT NULL CHECK (day_of_week BETWEEN 0 AND 6),
  start_time    TIME NOT NULL,
  end_time      TIME NOT NULL,
  consult_type  consultation_type_enum NOT NULL,
  is_active     BOOLEAN NOT NULL DEFAULT TRUE,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT valid_time_range CHECK (end_time > start_time)
);

CREATE INDEX idx_availability_doctor_day ON doctor_availability(doctor_id, day_of_week)
  WHERE is_active = TRUE;

-- ─────────────────────────────────────────────────────────────────────────────
-- AVAILABILITY OVERRIDES
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE availability_overrides (
  id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  doctor_id      UUID NOT NULL REFERENCES doctor_profiles(id) ON DELETE CASCADE,
  override_date  DATE NOT NULL,
  is_day_off     BOOLEAN NOT NULL DEFAULT FALSE,
  start_time     TIME,
  end_time       TIME,
  clinic_id      UUID REFERENCES clinics(id) ON DELETE SET NULL,
  reason         TEXT,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT override_has_times CHECK (
    is_day_off = TRUE OR (start_time IS NOT NULL AND end_time IS NOT NULL)
  ),
  CONSTRAINT override_valid_range CHECK (
    is_day_off = TRUE OR end_time > start_time
  ),
  UNIQUE (doctor_id, override_date)
);

-- ─────────────────────────────────────────────────────────────────────────────
-- COUPONS  (referenced by bookings — defined before bookings)
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE coupons (
  id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  code             TEXT NOT NULL UNIQUE,
  type             coupon_type_enum NOT NULL,
  applicable_to    coupon_applicable_enum NOT NULL DEFAULT 'BOTH',
  value            INTEGER NOT NULL,
  min_order_amount INTEGER NOT NULL DEFAULT 0,
  max_discount     INTEGER,
  usage_limit      INTEGER,
  per_user_limit   INTEGER NOT NULL DEFAULT 1,
  usage_count      INTEGER NOT NULL DEFAULT 0,
  valid_from       TIMESTAMPTZ NOT NULL,
  valid_until      TIMESTAMPTZ NOT NULL,
  is_active        BOOLEAN NOT NULL DEFAULT TRUE,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT valid_date_range CHECK (valid_until > valid_from),
  CONSTRAINT valid_percent CHECK (type != 'PERCENT' OR (value BETWEEN 1 AND 100))
);

CREATE INDEX idx_coupons_active ON coupons(code) WHERE is_active = TRUE;
CREATE INDEX idx_coupons_applicable ON coupons(applicable_to) WHERE is_active = TRUE;

-- ─────────────────────────────────────────────────────────────────────────────
-- BOOKINGS
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE bookings (
  id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  booking_ref         TEXT NOT NULL UNIQUE,
  doctor_id           UUID NOT NULL REFERENCES doctor_profiles(id),
  patient_id          UUID NOT NULL REFERENCES patient_profiles(id),
  family_member_id    UUID REFERENCES family_members(id),
  clinic_id           UUID REFERENCES clinics(id),
  slot_datetime       TIMESTAMPTZ NOT NULL,
  consult_type        consultation_type_enum NOT NULL,
  status              booking_status_enum NOT NULL DEFAULT 'PENDING_PAYMENT',
  patient_notes       TEXT,
  doctor_notes        TEXT,
  fee_charged         INTEGER NOT NULL,
  coupon_id           UUID REFERENCES coupons(id),
  discount_amount     INTEGER NOT NULL DEFAULT 0,
  cancellation_reason TEXT,
  cancelled_by        cancelled_by_enum,
  cancelled_at        TIMESTAMPTZ,
  confirmed_at        TIMESTAMPTZ,
  completed_at        TIMESTAMPTZ,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- v1.1: Partial unique index — PENDING_PAYMENT IS included (only one unresolved booking per slot).
-- Cannot be expressed in Prisma @@unique (no WHERE support). PG enforces this at DB level.
CREATE UNIQUE INDEX idx_bookings_slot_unique
  ON bookings(doctor_id, slot_datetime)
  WHERE status NOT IN (
    'CANCELLED_BY_PATIENT', 'CANCELLED_BY_DOCTOR',
    'CANCELLED_BY_SYSTEM', 'NO_SHOW'
  );

CREATE INDEX idx_bookings_doctor ON bookings(doctor_id, slot_datetime DESC);
CREATE INDEX idx_bookings_patient ON bookings(patient_id, created_at DESC);
CREATE INDEX idx_bookings_status ON bookings(status);
-- Index for BullMQ sweep job on stale PENDING_PAYMENT rows
CREATE INDEX idx_bookings_pending_expiry
  ON bookings(created_at)
  WHERE status = 'PENDING_PAYMENT';

-- ─────────────────────────────────────────────────────────────────────────────
-- PAYMENTS
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE payments (
  id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  booking_id            UUID NOT NULL UNIQUE REFERENCES bookings(id) ON DELETE CASCADE,
  razorpay_order_id     TEXT NOT NULL UNIQUE,
  razorpay_payment_id   TEXT UNIQUE,
  razorpay_signature    TEXT,
  status                payment_status_enum NOT NULL DEFAULT 'PENDING',
  amount_paise          INTEGER NOT NULL,
  currency              TEXT NOT NULL DEFAULT 'INR',
  method                TEXT,
  gateway_response      JSONB,
  paid_at               TIMESTAMPTZ,
  created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_payments_status ON payments(status);

-- ─────────────────────────────────────────────────────────────────────────────
-- WEBHOOK EVENTS  (v1.1 NEW — idempotency table)
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE webhook_events (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  provider      TEXT NOT NULL,
  event_id      TEXT NOT NULL,
  event_type    TEXT NOT NULL,
  payload       JSONB NOT NULL,
  processed_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_webhook_events UNIQUE (provider, event_id)
);

CREATE INDEX idx_webhook_events_provider_date
  ON webhook_events(provider, processed_at DESC);

-- ─────────────────────────────────────────────────────────────────────────────
-- REFUNDS
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE refunds (
  id                   UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  payment_id           UUID NOT NULL REFERENCES payments(id) ON DELETE CASCADE,
  razorpay_refund_id   TEXT UNIQUE,
  amount_paise         INTEGER NOT NULL,
  status               refund_status_enum NOT NULL DEFAULT 'PENDING',
  reason               TEXT,
  gateway_response     JSONB,
  created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at           TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_refunds_payment ON refunds(payment_id);

-- ─────────────────────────────────────────────────────────────────────────────
-- CONSULTATIONS
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE consultations (
  id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  booking_id            UUID NOT NULL UNIQUE REFERENCES bookings(id) ON DELETE CASCADE,
  hms_room_id           TEXT,
  hms_room_code_doctor  TEXT,
  hms_room_code_patient TEXT,
  started_at            TIMESTAMPTZ,
  ended_at              TIMESTAMPTZ,
  duration_seconds      INTEGER,
  status                consultation_status_enum NOT NULL DEFAULT 'WAITING',
  created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_consultations_status ON consultations(status)
  WHERE status IN ('WAITING', 'ACTIVE', 'TECHNICAL_FAILURE');

-- ─────────────────────────────────────────────────────────────────────────────
-- PRESCRIPTIONS
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE prescriptions (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  booking_id    UUID NOT NULL UNIQUE REFERENCES bookings(id) ON DELETE CASCADE,
  doctor_id     UUID NOT NULL REFERENCES doctor_profiles(id),
  patient_id    UUID NOT NULL REFERENCES patient_profiles(id),
  medicines_enc BYTEA NOT NULL DEFAULT '',
  diagnosis_enc BYTEA,
  advice_enc    BYTEA,
  follow_up_in  TEXT,
  pdf_url       TEXT,
  is_finalized  BOOLEAN NOT NULL DEFAULT FALSE,
  finalized_at  TIMESTAMPTZ,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT finalized_has_pdf CHECK (NOT is_finalized OR pdf_url IS NOT NULL)
);

CREATE INDEX idx_prescriptions_patient ON prescriptions(patient_id);
CREATE INDEX idx_prescriptions_doctor ON prescriptions(doctor_id);

-- ─────────────────────────────────────────────────────────────────────────────
-- REVIEWS
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE reviews (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  booking_id  UUID NOT NULL UNIQUE REFERENCES bookings(id),
  doctor_id   UUID NOT NULL REFERENCES doctor_profiles(id),
  patient_id  UUID NOT NULL REFERENCES patient_profiles(id),
  rating      INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5),
  comment     TEXT,
  tags        TEXT[] NOT NULL DEFAULT '{}',
  is_visible  BOOLEAN NOT NULL DEFAULT TRUE,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_reviews_doctor ON reviews(doctor_id, created_at DESC)
  WHERE is_visible = TRUE;

-- ─────────────────────────────────────────────────────────────────────────────
-- NOTIFICATIONS  (RANGE partitioned by month, 90-day archival)
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE notifications (
  id             UUID NOT NULL DEFAULT gen_random_uuid(),
  user_id        UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  type           notif_type_enum NOT NULL,
  channel        notif_channel_enum NOT NULL,
  title          TEXT NOT NULL,
  body           TEXT NOT NULL,
  data           JSONB,
  is_read        BOOLEAN NOT NULL DEFAULT FALSE,
  sent_at        TIMESTAMPTZ,
  read_at        TIMESTAMPTZ,
  status         notif_status_enum NOT NULL DEFAULT 'PENDING',
  error_message  TEXT,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (id, created_at)
) PARTITION BY RANGE (created_at);

-- Seed partitions (2026-05 through 2026-10).
-- Future months created by BullMQ maintenance job on 1st of each month.
CREATE TABLE notifications_2026_05 PARTITION OF notifications
  FOR VALUES FROM ('2026-05-01') TO ('2026-06-01');
CREATE TABLE notifications_2026_06 PARTITION OF notifications
  FOR VALUES FROM ('2026-06-01') TO ('2026-07-01');
CREATE TABLE notifications_2026_07 PARTITION OF notifications
  FOR VALUES FROM ('2026-07-01') TO ('2026-08-01');
CREATE TABLE notifications_2026_08 PARTITION OF notifications
  FOR VALUES FROM ('2026-08-01') TO ('2026-09-01');
CREATE TABLE notifications_2026_09 PARTITION OF notifications
  FOR VALUES FROM ('2026-09-01') TO ('2026-10-01');
CREATE TABLE notifications_2026_10 PARTITION OF notifications
  FOR VALUES FROM ('2026-10-01') TO ('2026-11-01');

CREATE INDEX idx_notifications_user ON notifications(user_id, created_at DESC);
CREATE INDEX idx_notifications_unread ON notifications(user_id)
  WHERE is_read = FALSE;

-- ─────────────────────────────────────────────────────────────────────────────
-- NOTIFICATION PREFERENCES  (v1.1 NEW)
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE notification_preferences (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  notif_type  notif_type_enum NOT NULL,
  channel     notif_channel_enum NOT NULL,
  is_enabled  BOOLEAN NOT NULL DEFAULT TRUE,
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_notif_pref UNIQUE (user_id, notif_type, channel)
);

-- ─────────────────────────────────────────────────────────────────────────────
-- COUPON REDEMPTIONS  (v1.1 NEW)
-- ─────────────────────────────────────────────────────────────────────────────
-- pharmacy_orders created after coupons but referenced here; coupons table
-- already exists at this point; pharmacy_orders created below.
-- FK to pharmacy_orders is deferred-style: added after pharmacy_orders creation.

CREATE TABLE coupon_redemptions (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  coupon_id    UUID NOT NULL REFERENCES coupons(id),
  user_id      UUID NOT NULL REFERENCES users(id),
  booking_id   UUID REFERENCES bookings(id),
  order_id     UUID,  -- FK to pharmacy_orders added below
  redeemed_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT one_of_booking_or_order CHECK (
    booking_id IS NOT NULL OR order_id IS NOT NULL
  )
);

CREATE INDEX idx_coupon_redemptions_lookup ON coupon_redemptions(coupon_id, user_id);

-- ─────────────────────────────────────────────────────────────────────────────
-- AUDIT LOGS  (RANGE partitioned by month, retained indefinitely)
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE audit_logs (
  id             UUID NOT NULL DEFAULT gen_random_uuid(),
  actor_id       UUID REFERENCES users(id) ON DELETE SET NULL,
  action         TEXT NOT NULL,
  resource_type  TEXT NOT NULL,
  resource_id    UUID,
  old_value      JSONB,
  new_value      JSONB,
  ip_address     TEXT,
  user_agent     TEXT,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (id, created_at)
) PARTITION BY RANGE (created_at);

CREATE TABLE audit_logs_2026_05 PARTITION OF audit_logs
  FOR VALUES FROM ('2026-05-01') TO ('2026-06-01');
CREATE TABLE audit_logs_2026_06 PARTITION OF audit_logs
  FOR VALUES FROM ('2026-06-01') TO ('2026-07-01');
CREATE TABLE audit_logs_2026_07 PARTITION OF audit_logs
  FOR VALUES FROM ('2026-07-01') TO ('2026-08-01');
CREATE TABLE audit_logs_2026_08 PARTITION OF audit_logs
  FOR VALUES FROM ('2026-08-01') TO ('2026-09-01');
CREATE TABLE audit_logs_2026_09 PARTITION OF audit_logs
  FOR VALUES FROM ('2026-09-01') TO ('2026-10-01');
CREATE TABLE audit_logs_2026_10 PARTITION OF audit_logs
  FOR VALUES FROM ('2026-10-01') TO ('2026-11-01');

CREATE INDEX idx_audit_actor ON audit_logs(actor_id, created_at DESC);
CREATE INDEX idx_audit_resource ON audit_logs(resource_type, resource_id);

-- ─────────────────────────────────────────────────────────────────────────────
-- PAYOUTS  (defined before doctor_earnings — doctor_earnings FK → payouts)
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE payouts (
  id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  doctor_id           UUID NOT NULL REFERENCES doctor_profiles(id),
  amount_paise        INTEGER NOT NULL,
  status              payout_status_enum NOT NULL DEFAULT 'REQUESTED',
  utr_number          TEXT,
  bank_account_last4  TEXT,
  requested_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  processed_at        TIMESTAMPTZ,
  processed_by        UUID REFERENCES users(id),
  notes               TEXT
);

CREATE INDEX idx_payouts_doctor ON payouts(doctor_id, requested_at DESC);
CREATE INDEX idx_payouts_status ON payouts(status) WHERE status = 'REQUESTED';

-- ─────────────────────────────────────────────────────────────────────────────
-- DOCTOR EARNINGS
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE doctor_earnings (
  id                        UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  doctor_id                 UUID NOT NULL REFERENCES doctor_profiles(id),
  booking_id                UUID NOT NULL UNIQUE REFERENCES bookings(id),
  gross_amount_paise        INTEGER NOT NULL,
  platform_commission_paise INTEGER NOT NULL,
  net_amount_paise          INTEGER NOT NULL,
  is_paid_out               BOOLEAN NOT NULL DEFAULT FALSE,
  payout_id                 UUID REFERENCES payouts(id),
  created_at                TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT earnings_sum CHECK (
    net_amount_paise = gross_amount_paise - platform_commission_paise
  )
);

CREATE INDEX idx_earnings_doctor_unpaid ON doctor_earnings(doctor_id)
  WHERE is_paid_out = FALSE;

-- ─────────────────────────────────────────────────────────────────────────────
-- AUTH & VERIFICATION TABLES  (v1.1 NEW)
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE password_resets (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  token_hash  TEXT NOT NULL,
  expires_at  TIMESTAMPTZ NOT NULL,
  used_at     TIMESTAMPTZ,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_password_resets_user ON password_resets(user_id, expires_at)
  WHERE used_at IS NULL;

CREATE TABLE phone_verifications (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  phone_hash   TEXT NOT NULL,
  otp_hash     TEXT NOT NULL,
  purpose      TEXT NOT NULL,
  attempts     INTEGER NOT NULL DEFAULT 0,
  expires_at   TIMESTAMPTZ NOT NULL,
  verified_at  TIMESTAMPTZ,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_phone_verifications_hash_purpose
  ON phone_verifications(phone_hash, purpose, expires_at)
  WHERE verified_at IS NULL;

CREATE TABLE email_verifications (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id      UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  token_hash   TEXT NOT NULL,
  expires_at   TIMESTAMPTZ NOT NULL,
  verified_at  TIMESTAMPTZ,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_email_verifications_user
  ON email_verifications(user_id, expires_at)
  WHERE verified_at IS NULL;

-- ─────────────────────────────────────────────────────────────────────────────
-- SYSTEM SETTINGS  (v1.1 NEW)
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE system_settings (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  key          TEXT NOT NULL UNIQUE,
  value        JSONB NOT NULL,
  description  TEXT,
  updated_by   UUID REFERENCES users(id),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ─────────────────────────────────────────────────────────────────────────────
-- BLOG
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE blog_categories (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name        TEXT NOT NULL UNIQUE,
  slug        TEXT NOT NULL UNIQUE,
  description TEXT,
  is_active   BOOLEAN NOT NULL DEFAULT TRUE,
  sort_order  INTEGER NOT NULL DEFAULT 0,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE blog_posts (
  id                      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title                   TEXT NOT NULL,
  slug                    TEXT NOT NULL UNIQUE,
  excerpt                 TEXT,
  content_markdown        TEXT NOT NULL,
  cover_image_url         TEXT,
  author_id               UUID NOT NULL REFERENCES users(id),
  category_id             UUID REFERENCES blog_categories(id),
  speciality_id           UUID REFERENCES specialities(id),
  tags                    TEXT[] NOT NULL DEFAULT '{}',
  seo_title               TEXT,
  seo_description         TEXT,
  og_image_url            TEXT,
  estimated_read_minutes  INTEGER NOT NULL DEFAULT 3,
  status                  blog_status_enum NOT NULL DEFAULT 'DRAFT',
  published_at            TIMESTAMPTZ,
  created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at              TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_blog_posts_published ON blog_posts(published_at DESC)
  WHERE status = 'PUBLISHED';
CREATE INDEX idx_blog_posts_category ON blog_posts(category_id)
  WHERE status = 'PUBLISHED';
CREATE INDEX idx_blog_posts_speciality ON blog_posts(speciality_id)
  WHERE status = 'PUBLISHED';

-- ─────────────────────────────────────────────────────────────────────────────
-- PHARMACY
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE pharmacy_categories (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name       TEXT NOT NULL UNIQUE,
  slug       TEXT NOT NULL UNIQUE,
  is_active  BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE pharmacy_products (
  id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name                  TEXT NOT NULL,
  generic_name          TEXT,
  manufacturer          TEXT,
  sku                   TEXT NOT NULL UNIQUE,
  price_paise           INTEGER NOT NULL,
  mrp_paise             INTEGER NOT NULL,
  stock_quantity        INTEGER NOT NULL DEFAULT 0,
  prescription_required BOOLEAN NOT NULL DEFAULT FALSE,
  image_url             TEXT,
  category_id           UUID REFERENCES pharmacy_categories(id),
  description           TEXT,
  is_active             BOOLEAN NOT NULL DEFAULT TRUE,
  created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT valid_price CHECK (price_paise <= mrp_paise)
);

CREATE INDEX idx_pharmacy_products_active ON pharmacy_products(category_id)
  WHERE is_active = TRUE;
CREATE INDEX idx_pharmacy_products_rx ON pharmacy_products(prescription_required)
  WHERE is_active = TRUE;

CREATE TABLE pharmacy_orders (
  id                       UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  order_ref                TEXT NOT NULL UNIQUE,
  patient_id               UUID NOT NULL REFERENCES patient_profiles(id),
  items                    JSONB NOT NULL,
  subtotal_paise           INTEGER NOT NULL,
  delivery_charge_paise    INTEGER NOT NULL DEFAULT 0,
  discount_paise           INTEGER NOT NULL DEFAULT 0,
  total_paise              INTEGER NOT NULL,
  coupon_id                UUID REFERENCES coupons(id),
  delivery_address         JSONB NOT NULL,
  prescription_url         TEXT,
  status                   pharmacy_order_status_enum NOT NULL DEFAULT 'PLACED',
  notes                    TEXT,
  placed_at                TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at               TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT order_total_check CHECK (
    total_paise = subtotal_paise + delivery_charge_paise - discount_paise
  )
);

CREATE INDEX idx_pharmacy_orders_patient ON pharmacy_orders(patient_id, placed_at DESC);
CREATE INDEX idx_pharmacy_orders_status ON pharmacy_orders(status)
  WHERE status NOT IN ('DELIVERED', 'CANCELLED');

-- ─────────────────────────────────────────────────────────────────────────────
-- BACK-FILL: FK from coupon_redemptions.order_id → pharmacy_orders
-- ─────────────────────────────────────────────────────────────────────────────
ALTER TABLE coupon_redemptions
  ADD CONSTRAINT coupon_redemptions_order_id_fkey
  FOREIGN KEY (order_id) REFERENCES pharmacy_orders(id);

-- ─────────────────────────────────────────────────────────────────────────────
-- PRISMA MIGRATION METADATA
-- ─────────────────────────────────────────────────────────────────────────────
-- Prisma reads this table to track applied migrations.
INSERT INTO "_prisma_migrations" (
  id, checksum, finished_at, migration_name,
  logs, rolled_back_at, started_at, applied_steps_count
) VALUES (
  gen_random_uuid()::text,
  'docnear_v1_init_manual',
  NOW(),
  '20260521000000_v1_init',
  NULL, NULL, NOW(), 1
);

COMMIT;
